export const ADD_TASKS_LOADING="add/tasks/loading"
export const ADD_TASKS_SUCCESS="add/tasks/success"
export const ADD_TASKS_ERROR="add/tasks/error"
export const REMOVE_TASKS_LOADING="remove/tasks/loading"
export const REMOVE_TASKS_SUCCESS="remove/tasks/success"
export const REMOVE_TASKS_ERROR="remove/tasks/error"
export const UPDATE_TASKS_LOADING="update/tasks/loading"
export const UPDATE_TASKS_SUCCESS="update/tasks/success"
export const UPDATE_TASKS_ERROR="update/tasks/error"
export const GET_TASKS_LOADING="get/tasks/loading"
export const GET_TASKS_SUCCESS="get/tasks/success"
export const GET_TASKS_ERROR="get/tasks/error"

